import type {
  Course,
  Instructor,
  Learner,
  Enrollment,
  Certificate,
  TeamMember,
  WorkflowInstance,
  DashboardKPIs,
  RevenueData,
  CourseAnalytics,
  InstructorAnalytics,
  User,
} from "@/types/lms";

export const mockInstructors: Instructor[] = [
  {
    id: "ins-1",
    name: "Sarah Johnson",
    email: "sarah.johnson@example.com",
    avatar: undefined,
    activeCourses: 5,
    totalEnrolled: 1250,
    avgCompletionRate: 78,
    totalRevenue: 45600,
  },
  {
    id: "ins-2",
    name: "Michael Chen",
    email: "michael.chen@example.com",
    avatar: undefined,
    activeCourses: 3,
    totalEnrolled: 890,
    avgCompletionRate: 82,
    totalRevenue: 32100,
  },
  {
    id: "ins-3",
    name: "Emily Rodriguez",
    email: "emily.rodriguez@example.com",
    avatar: undefined,
    activeCourses: 4,
    totalEnrolled: 1100,
    avgCompletionRate: 75,
    totalRevenue: 38900,
  },
  {
    id: "ins-4",
    name: "David Kim",
    email: "david.kim@example.com",
    avatar: undefined,
    activeCourses: 2,
    totalEnrolled: 450,
    avgCompletionRate: 88,
    totalRevenue: 18900,
  },
  {
    id: "ins-5",
    name: "Lisa Thompson",
    email: "lisa.thompson@example.com",
    avatar: undefined,
    activeCourses: 6,
    totalEnrolled: 1500,
    avgCompletionRate: 71,
    totalRevenue: 52300,
  },
];

export const mockCourses: Course[] = [
  {
    id: "course-1",
    title: "Complete React Development",
    slug: "complete-react-development",
    instructorId: "ins-1",
    instructor: mockInstructors[0],
    category: "Web Development",
    status: "published",
    level: "intermediate",
    price: 99,
    compareAtPrice: 149,
    currency: "USD",
    enrolledCount: 450,
    moduleCount: 12,
    rating: 4.8,
    reviewCount: 156,
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2024-02-01T08:00:00Z",
    description: "Master React from fundamentals to advanced patterns",
  },
  {
    id: "course-2",
    title: "Python for Data Science",
    slug: "python-for-data-science",
    instructorId: "ins-2",
    instructor: mockInstructors[1],
    category: "Data Science",
    status: "published",
    level: "beginner",
    price: 79,
    currency: "USD",
    enrolledCount: 380,
    moduleCount: 15,
    rating: 4.6,
    reviewCount: 98,
    createdAt: "2024-01-10T09:00:00Z",
    updatedAt: "2024-01-28T14:00:00Z",
    description: "Learn Python and data analysis from scratch",
  },
  {
    id: "course-3",
    title: "Advanced TypeScript Patterns",
    slug: "advanced-typescript-patterns",
    instructorId: "ins-1",
    instructor: mockInstructors[0],
    category: "Web Development",
    status: "under-review",
    level: "advanced",
    price: 129,
    currency: "USD",
    enrolledCount: 0,
    moduleCount: 8,
    rating: 0,
    reviewCount: 0,
    createdAt: "2024-02-01T11:00:00Z",
    updatedAt: "2024-02-10T16:00:00Z",
    submittedAt: "2024-02-10T16:00:00Z",
    description: "Deep dive into advanced TypeScript patterns",
  },
  {
    id: "course-4",
    title: "UI/UX Design Fundamentals",
    slug: "ui-ux-design-fundamentals",
    instructorId: "ins-3",
    instructor: mockInstructors[2],
    category: "Design",
    status: "published",
    level: "beginner",
    price: 59,
    compareAtPrice: 89,
    currency: "USD",
    enrolledCount: 520,
    moduleCount: 10,
    rating: 4.9,
    reviewCount: 203,
    createdAt: "2024-01-05T08:00:00Z",
    updatedAt: "2024-02-05T10:00:00Z",
    description:
      "Learn the fundamentals of user interface and experience design",
  },
  {
    id: "course-5",
    title: "Machine Learning Basics",
    slug: "machine-learning-basics",
    instructorId: "ins-2",
    instructor: mockInstructors[1],
    category: "Data Science",
    status: "draft",
    level: "intermediate",
    price: 149,
    currency: "USD",
    enrolledCount: 0,
    moduleCount: 5,
    rating: 0,
    reviewCount: 0,
    createdAt: "2024-02-08T14:00:00Z",
    updatedAt: "2024-02-12T09:00:00Z",
    description: "Introduction to machine learning concepts",
  },
  {
    id: "course-6",
    title: "Node.js Backend Development",
    slug: "nodejs-backend-development",
    instructorId: "ins-4",
    instructor: mockInstructors[3],
    category: "Web Development",
    status: "under-review",
    level: "intermediate",
    price: 89,
    currency: "USD",
    enrolledCount: 0,
    moduleCount: 11,
    rating: 0,
    reviewCount: 0,
    createdAt: "2024-01-20T12:00:00Z",
    updatedAt: "2024-02-11T11:00:00Z",
    submittedAt: "2024-02-11T11:00:00Z",
    description: "Build scalable backend applications with Node.js",
  },
  {
    id: "course-7",
    title: "Docker & Kubernetes Mastery",
    slug: "docker-kubernetes-mastery",
    instructorId: "ins-5",
    instructor: mockInstructors[4],
    category: "DevOps",
    status: "published",
    level: "advanced",
    price: 169,
    currency: "USD",
    enrolledCount: 280,
    moduleCount: 14,
    rating: 4.7,
    reviewCount: 67,
    createdAt: "2024-01-12T10:00:00Z",
    updatedAt: "2024-02-08T15:00:00Z",
    description: "Master containerization and orchestration",
  },
  {
    id: "course-8",
    title: "AWS Cloud Practitioner",
    slug: "aws-cloud-practitioner",
    instructorId: "ins-5",
    instructor: mockInstructors[4],
    category: "Cloud",
    status: "archived",
    level: "beginner",
    price: 0,
    currency: "USD",
    enrolledCount: 890,
    moduleCount: 20,
    rating: 4.5,
    reviewCount: 312,
    createdAt: "2023-06-01T09:00:00Z",
    updatedAt: "2024-01-15T08:00:00Z",
    description: "Prepare for AWS Cloud Practitioner certification",
  },
];

export const mockLearners: Learner[] = [
  {
    id: "learn-1",
    name: "Alex Turner",
    email: "alex.turner@example.com",
    avatar: undefined,
    enrolledCourseCount: 3,
    completedCourses: 1,
    certificatesEarned: 1,
    lastActive: "2024-02-12T14:30:00Z",
    status: "active",
    joinedAt: "2023-11-15T10:00:00Z",
  },
  {
    id: "learn-2",
    name: "Maria Garcia",
    email: "maria.garcia@example.com",
    avatar: undefined,
    enrolledCourseCount: 5,
    completedCourses: 3,
    certificatesEarned: 3,
    lastActive: "2024-02-12T16:45:00Z",
    status: "active",
    joinedAt: "2023-09-20T08:00:00Z",
  },
  {
    id: "learn-3",
    name: "James Wilson",
    email: "james.wilson@example.com",
    avatar: undefined,
    enrolledCourseCount: 2,
    completedCourses: 0,
    certificatesEarned: 0,
    lastActive: "2024-02-10T09:15:00Z",
    status: "active",
    joinedAt: "2024-01-05T11:00:00Z",
  },
  {
    id: "learn-4",
    name: "Emma Brown",
    email: "emma.brown@example.com",
    avatar: undefined,
    enrolledCourseCount: 8,
    completedCourses: 6,
    certificatesEarned: 6,
    lastActive: "2024-02-11T18:20:00Z",
    status: "active",
    joinedAt: "2023-05-10T14:00:00Z",
  },
  {
    id: "learn-5",
    name: "Robert Miller",
    email: "robert.miller@example.com",
    avatar: undefined,
    enrolledCourseCount: 1,
    completedCourses: 0,
    certificatesEarned: 0,
    lastActive: "2024-01-28T11:00:00Z",
    status: "suspended",
    joinedAt: "2023-12-01T09:00:00Z",
  },
  {
    id: "learn-6",
    name: "Sophie Davis",
    email: "sophie.davis@example.com",
    avatar: undefined,
    enrolledCourseCount: 4,
    completedCourses: 2,
    certificatesEarned: 2,
    lastActive: "2024-02-12T10:30:00Z",
    status: "active",
    joinedAt: "2023-08-15T16:00:00Z",
  },
  {
    id: "learn-7",
    name: "Daniel Lee",
    email: "daniel.lee@example.com",
    avatar: undefined,
    enrolledCourseCount: 2,
    completedCourses: 2,
    certificatesEarned: 2,
    lastActive: "2024-02-09T14:00:00Z",
    status: "active",
    joinedAt: "2023-10-20T12:00:00Z",
  },
  {
    id: "learn-8",
    name: "Olivia Martinez",
    email: "olivia.martinez@example.com",
    avatar: undefined,
    enrolledCourseCount: 6,
    completedCourses: 4,
    certificatesEarned: 4,
    lastActive: "2024-02-12T08:45:00Z",
    status: "active",
    joinedAt: "2023-07-25T10:00:00Z",
  },
];

export const mockEnrollments: Enrollment[] = [
  {
    id: "enr-1",
    learnerId: "learn-1",
    learner: mockLearners[0],
    courseId: "course-1",
    course: mockCourses[0],
    status: "active",
    enrolledAt: "2024-01-15T10:00:00Z",
    completionPct: 65,
    pricePaid: 99,
    currency: "USD",
    expiresAt: "2025-01-15T10:00:00Z",
  },
  {
    id: "enr-2",
    learnerId: "learn-1",
    learner: mockLearners[0],
    courseId: "course-2",
    course: mockCourses[1],
    status: "completed",
    enrolledAt: "2023-11-20T09:00:00Z",
    completedAt: "2024-01-10T15:00:00Z",
    completionPct: 100,
    pricePaid: 79,
    currency: "USD",
  },
  {
    id: "enr-3",
    learnerId: "learn-2",
    learner: mockLearners[1],
    courseId: "course-1",
    course: mockCourses[0],
    status: "active",
    enrolledAt: "2024-01-18T11:00:00Z",
    completionPct: 42,
    pricePaid: 99,
    currency: "USD",
  },
  {
    id: "enr-4",
    learnerId: "learn-2",
    learner: mockLearners[1],
    courseId: "course-4",
    course: mockCourses[3],
    status: "completed",
    enrolledAt: "2023-10-05T08:00:00Z",
    completedAt: "2023-12-20T14:00:00Z",
    completionPct: 100,
    pricePaid: 59,
    currency: "USD",
  },
  {
    id: "enr-5",
    learnerId: "learn-3",
    learner: mockLearners[2],
    courseId: "course-7",
    course: mockCourses[6],
    status: "active",
    enrolledAt: "2024-02-01T14:00:00Z",
    completionPct: 15,
    pricePaid: 169,
    currency: "USD",
  },
  {
    id: "enr-6",
    learnerId: "learn-4",
    learner: mockLearners[3],
    courseId: "course-1",
    course: mockCourses[0],
    status: "completed",
    enrolledAt: "2023-09-10T10:00:00Z",
    completedAt: "2023-11-15T16:00:00Z",
    completionPct: 100,
    pricePaid: 99,
    currency: "USD",
  },
  {
    id: "enr-7",
    learnerId: "learn-4",
    learner: mockLearners[3],
    courseId: "course-2",
    course: mockCourses[1],
    status: "completed",
    enrolledAt: "2023-08-20T09:00:00Z",
    completedAt: "2023-10-30T11:00:00Z",
    completionPct: 100,
    pricePaid: 79,
    currency: "USD",
  },
  {
    id: "enr-8",
    learnerId: "learn-5",
    learner: mockLearners[4],
    courseId: "course-4",
    course: mockCourses[3],
    status: "expired",
    enrolledAt: "2023-12-01T12:00:00Z",
    completionPct: 23,
    pricePaid: 59,
    currency: "USD",
    expiresAt: "2024-02-01T12:00:00Z",
  },
];

export const mockCertificates: Certificate[] = [
  {
    id: "cert-1",
    verificationCode: "LMS-A1B2C3D4",
    learnerId: "learn-1",
    learner: mockLearners[0],
    courseId: "course-2",
    course: mockCourses[1],
    issuedAt: "2024-01-10T15:00:00Z",
    expiresAt: "2025-01-10T15:00:00Z",
    revoked: false,
    templateTitle: "Certificate of Completion",
  },
  {
    id: "cert-2",
    verificationCode: "LMS-E5F6G7H8",
    learnerId: "learn-2",
    learner: mockLearners[1],
    courseId: "course-4",
    course: mockCourses[3],
    issuedAt: "2023-12-20T14:00:00Z",
    revoked: false,
    templateTitle: "Certificate of Completion",
  },
  {
    id: "cert-3",
    verificationCode: "LMS-I9J0K1L2",
    learnerId: "learn-4",
    learner: mockLearners[3],
    courseId: "course-1",
    course: mockCourses[0],
    issuedAt: "2023-11-15T16:00:00Z",
    revoked: false,
    templateTitle: "Certificate of Completion",
  },
  {
    id: "cert-4",
    verificationCode: "LMS-M3N4O5P6",
    learnerId: "learn-4",
    learner: mockLearners[3],
    courseId: "course-2",
    course: mockCourses[1],
    issuedAt: "2023-10-30T11:00:00Z",
    revoked: false,
    templateTitle: "Certificate of Completion",
  },
  {
    id: "cert-5",
    verificationCode: "LMS-Q7R8S9T0",
    learnerId: "learn-7",
    learner: mockLearners[6],
    courseId: "course-4",
    course: mockCourses[3],
    issuedAt: "2024-01-05T10:00:00Z",
    expiresAt: "2025-01-05T10:00:00Z",
    revoked: true,
    revokedAt: "2024-02-01T09:00:00Z",
    revokedReason: "Academic integrity violation",
    templateTitle: "Certificate of Completion",
  },
  {
    id: "cert-6",
    verificationCode: "LMS-U1V2W3X4",
    learnerId: "learn-6",
    learner: mockLearners[5],
    courseId: "course-1",
    course: mockCourses[0],
    issuedAt: "2024-02-05T14:00:00Z",
    expiresAt: "2025-02-05T14:00:00Z",
    revoked: false,
    templateTitle: "Certificate of Completion",
  },
];

export const mockTeamMembers: TeamMember[] = [
  {
    id: "team-1",
    name: "Admin User",
    email: "admin@example.com",
    role: "lms-admin",
    avatar: undefined,
    invitedAt: "2023-01-01T00:00:00Z",
    lastActive: "2024-02-12T18:00:00Z",
  },
  {
    id: "team-2",
    name: "Content Reviewer 1",
    email: "reviewer1@example.com",
    role: "content-reviewer",
    avatar: undefined,
    invitedAt: "2023-06-15T10:00:00Z",
    lastActive: "2024-02-12T16:30:00Z",
  },
  {
    id: "team-3",
    name: "Content Reviewer 2",
    email: "reviewer2@example.com",
    role: "content-reviewer",
    avatar: undefined,
    invitedAt: "2023-08-20T14:00:00Z",
    lastActive: "2024-02-11T09:00:00Z",
  },
];

export const mockWorkflowInstances: WorkflowInstance[] = [
  {
    id: "wf-1",
    courseId: "course-3",
    course: mockCourses[2],
    stage: "content-check",
    tasks: [
      {
        id: "task-1",
        label: "Review all modules for quality and accuracy",
        status: "pending",
        requiredRole: "content-reviewer",
      },
      {
        id: "task-2",
        label: "Check media assets load correctly",
        status: "pending",
        requiredRole: "content-reviewer",
      },
    ],
    submittedAt: "2024-02-10T16:00:00Z",
    currentAssignee: "team-2",
  },
  {
    id: "wf-2",
    courseId: "course-6",
    course: mockCourses[5],
    stage: "content-check",
    tasks: [
      {
        id: "task-3",
        label: "Review all modules for quality and accuracy",
        status: "completed",
        requiredRole: "content-reviewer",
      },
      {
        id: "task-4",
        label: "Check media assets load correctly",
        status: "in_progress",
        requiredRole: "content-reviewer",
      },
    ],
    submittedAt: "2024-02-11T11:00:00Z",
    currentAssignee: "team-3",
  },
];

export const mockDashboardKPIs: DashboardKPIs = {
  totalActiveLearners: 2847,
  totalCourses: 45,
  enrollmentsThisMonth: 523,
  revenueThisMonth: 42890,
  completionRate: 72,
  certificatesIssued: 892,
};

export const mockRevenueData: RevenueData[] = [
  { date: "2024-01-01", realized: 12500, deferred: 4200 },
  { date: "2024-01-08", realized: 15800, deferred: 5100 },
  { date: "2024-01-15", realized: 18200, deferred: 6300 },
  { date: "2024-01-22", realized: 16500, deferred: 5800 },
  { date: "2024-01-29", realized: 21000, deferred: 7200 },
  { date: "2024-02-05", realized: 19800, deferred: 6900 },
  { date: "2024-02-12", realized: 23400, deferred: 8100 },
];

export const mockCourseAnalytics: CourseAnalytics[] = [
  {
    courseId: "course-1",
    courseTitle: "Complete React Development",
    enrollments: 450,
    completionRate: 78,
    avgScore: 85,
    rating: 4.8,
    revenue: 44550,
  },
  {
    courseId: "course-2",
    courseTitle: "Python for Data Science",
    enrollments: 380,
    completionRate: 72,
    avgScore: 82,
    rating: 4.6,
    revenue: 30020,
  },
  {
    courseId: "course-4",
    courseTitle: "UI/UX Design Fundamentals",
    enrollments: 520,
    completionRate: 85,
    avgScore: 88,
    rating: 4.9,
    revenue: 30680,
  },
  {
    courseId: "course-7",
    courseTitle: "Docker & Kubernetes Mastery",
    enrollments: 280,
    completionRate: 68,
    avgScore: 79,
    rating: 4.7,
    revenue: 47320,
  },
  {
    courseId: "course-8",
    courseTitle: "AWS Cloud Practitioner",
    enrollments: 890,
    completionRate: 62,
    avgScore: 75,
    rating: 4.5,
    revenue: 0,
  },
];

export const mockInstructorAnalytics: InstructorAnalytics[] = [
  {
    instructorId: "ins-1",
    instructorName: "Sarah Johnson",
    activeCourses: 5,
    totalEnrolled: 1250,
    avgCompletionRate: 78,
    totalRevenue: 45600,
  },
  {
    instructorId: "ins-2",
    instructorName: "Michael Chen",
    activeCourses: 3,
    totalEnrolled: 890,
    avgCompletionRate: 82,
    totalRevenue: 32100,
  },
  {
    instructorId: "ins-3",
    instructorName: "Emily Rodriguez",
    activeCourses: 4,
    totalEnrolled: 1100,
    avgCompletionRate: 75,
    totalRevenue: 38900,
  },
  {
    instructorId: "ins-4",
    instructorName: "David Kim",
    activeCourses: 2,
    totalEnrolled: 450,
    avgCompletionRate: 88,
    totalRevenue: 18900,
  },
  {
    instructorId: "ins-5",
    instructorName: "Lisa Thompson",
    activeCourses: 6,
    totalEnrolled: 1500,
    avgCompletionRate: 71,
    totalRevenue: 52300,
  },
];

export const mockPlatformSettings = {
  platformName: "LearnHub",
  supportEmail: "support@learnhub.com",
  defaultTimezone: "America/New_York",
  completionThreshold: 80,
};

export const mockPaymentSettings = {
  activeGateway: "stripe" as const,
  stripeApiKey: "sk_test_************************",
  stripeWebhookSecret: "whsec_************************",
  razorpayKeyId: "rzp_test_************************",
  razorpayWebhookSecret: "whsec_razorpay_************************",
  supportedCurrencies: ["USD", "EUR", "GBP"],
};

export const mockUser: User = {
  id: "user-1",
  email: "admin@example.com",
  name: "Admin User",
  role: "lms-admin",
  avatar: undefined,
};

export const categories = [
  "Web Development",
  "Data Science",
  "Design",
  "DevOps",
  "Cloud",
  "Mobile Development",
  "Business",
  "Marketing",
];

export const courseStatuses: Array<{ value: string; label: string }> = [
  { value: "draft", label: "Draft" },
  { value: "under-review", label: "Under Review" },
  { value: "published", label: "Published" },
  { value: "archived", label: "Archived" },
];

export const enrollmentStatuses: Array<{ value: string; label: string }> = [
  { value: "active", label: "Active" },
  { value: "completed", label: "Completed" },
  { value: "expired", label: "Expired" },
  { value: "cancelled", label: "Cancelled" },
];

export const learnerStatuses: Array<{ value: string; label: string }> = [
  { value: "active", label: "Active" },
  { value: "suspended", label: "Suspended" },
];

export const timezones = [
  "America/New_York",
  "America/Los_Angeles",
  "America/Chicago",
  "Europe/London",
  "Europe/Paris",
  "Asia/Tokyo",
  "Asia/Singapore",
  "Australia/Sydney",
];

export const currencies = ["USD", "EUR", "GBP", "INR", "AUD", "CAD"];
